### ISSUE TITLE
Create a new dialog function

### ISSUE THREAD

**Issue by Luke123443** [liride/Liride#1]
This function is used in all the tasks that need a user interaction, for example quitting without saving a file exetera.

```js
	this.genDialog = function( message, callback ) {
		
		//Send callback( status ) where status == false if the user refuses
		
		//Send callback( status ) where status == true if the user accepts
		
		//This will also handle the styling of the box and it's going to be fully customizable
		
	}

```

I'm probably going to implement this also in liride theme, just to give users an example of "how to modify" default functions

**Comment by liride** [comment]
Relate to #3 to finish this issue.
